name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_modular: ^6.4.1
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.16.0
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
