name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.8.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_modular: ^6.4.1
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  meta: ^1.16.0
  mocktail: ^1.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
